# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: MyComputerAgent
    

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    allowUnstable: true
    addToPath: true
    architecture: 'x64'

- script: |
    # Commands to build your Python project and generate output files
    # For example, if you're using pip:
    pip install .
  displayName: 'Build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
    